# Generated by Django 3.2.16 on 2023-02-03 16:33

from django.db import migrations


def populate_categories(apps, schema_editor):
    Category = apps.get_model('bridgeapp', 'Category')

    categories = [
        'Pre-commitment',
        'In-custody',
        'Post-release',
    ]
    for category in categories:
        Category.objects.create(type=category)


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_categories)
    ]
