# Generated by Django 3.2.16 on 2023-02-03 13:58

import os
from django.db import migrations


def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(is_superuser=True).first():
        user = User.objects.create(
            username = os.environ.get('SUPERUSER_USERNAME'),
            email = os.environ.get('SUPERUSER_EMAIL'),
            is_superuser = True,
        )
        user.set_password(os.environ.get('SUPERUSER_PASSWORD'))
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bridgeapp', '0004_alter_response_body_alter_thread_body'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
